app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager

class User(db.Model, UserMixin):
    __tablename__='users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(225))
    email = db.Column(db.String(255),unique=True)
    pass_secure = db.Column(db.String(255))
    profile_image = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy='dynamic')
    comments = db.relationship('Comment', backref = 'user', lazy= 'dynamic')
    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def password(self):
        raise AttributeError('You cant read password attribute')
    
    def password(self,password):
        self.pass_secure = generate_password_hash(password)
        
    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)
    
    def __repr__(self):
        return f'User {self.username}'
    
class Pitch(db.Model):
    __tablename__ ='pitches'
    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(255))
    mintute_pitch = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref = 'pitch', lazy= 'dynamic')
    
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
        
    def get_pitch_by_category(cls, category):
        pitches = Pitch.query.filter_by(category=category).all()
        
        return pitches
    def get_pitch_by_id(cls, id):
        all_pitches = Pitch.query.filter_by(id = id).all()
        return all_pitches
    
class Comment(db.Model):
    __tablename__='comments'
    id = db.Column(db.Integer,primary_key=True)
    comment = db.Column(db.String(255))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    
    def get_comments(pitch_id):
        comments = Comment.query.filter_by(pitch_id=pitch_id).all()
        return comments
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, TextAreaField
from wtforms.validators import Required
from wtforms import ValidationError
from ..models import Pitch


class PitchForm(FlaskForm):
    # pitch_choices =[('promotion-pitch', 'Promotion Pitch'), ('interview-pitch, Interview Pitch'),('mvp-pitch, MVP pitch '),('pickup-lines', 'Pickup Lines')]
    pitch_cat = SelectField(u'Pitch Type', choices=[('Interview-Pitch', 'Interview'), ('Promotion-Pitch', 'Promotion'), ('Product-Pitch', 'Product')],validators=[Required()])
    pitch = TextAreaField('Enter your pitch', validators=[Required()])
    submit = SubmitField('Pitch')
    
    
class CommentForm(FlaskForm):
    opinion = TextAreaField('Enter your comment', validators=[Required()])
    submit = SubmitField('Add Comment')
    

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail



db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)
    
    app.config.from_object(config_options[config_name])
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    configure_uploads(app,photos)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')
    
    
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views,forms

app/main/views.py
from flask import render_template,redirect, url_for,request,flash
from . import main
from .forms import PitchForm, CommentForm
from flask_login import current_user, login_required
from ..models import Pitch,Comment,User
from .. import photos,db

@main.route('/')
def home():
    pitches = Pitch.query.all()
    
    return render_template('home.html',pitches=pitches)


@main.route('/add',methods = ["GET", "POST"])
@login_required
def add_pitch():
    pitch_form = PitchForm()
    if pitch_form.validate_on_submit():
        p_category = pitch_form.pitch_cat.data
        create_pitch = Pitch(category= p_category, mintute_pitch=pitch_form.pitch.data, user=current_user)
        create_pitch.save_pitch()
        return redirect(url_for('main.home'))
    return render_template('pitch.html', pitch_form=pitch_form)

@main.route('/addcomment/<int:id>', methods = ["GET", "POST"])
@login_required
def add_comment(id):
    comment_form = CommentForm()
    pitch_comment = Pitch.query.get(id)
    if comment_form.validate_on_submit():
        new_comment = Comment(comment= comment_form.opinion.data, user=current_user,pitch=pitch_comment)
        new_comment.save_comment()

        return redirect(url_for('main.home'))
    # flash(u'Successfully added comment', 'success')
    return render_template('addcomments.html',comment_form=comment_form, pitch_comment=pitch_comment)

@main.route('/viewcomments/<int:id>')
@login_required
def fet_comments(id):
    fetch_comments = Comment.query.filter_by(pitch_id= id).all()
    
    return render_template('viewcomments.html', fetch_comments=fetch_comments)
    
@main.route('/profile/<int:id>')
def user_profile(id):
    user = current_user
    
    pitches = Pitch.query.filter_by(user_id= id).all()
    
    return render_template('prof/profile.html', pitches=pitches, user=user)

@main.route('/updatepic/<int:id>', methods=['POST'])
def update_pic(id):
    user = User.query.filter_by(id = id).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_image = path
        db.session.commit()
    return redirect(url_for('main.user_profile', id= id))

@main.route('/promotions')
def get_promotions():
    promotion_pitches = Pitch.query.filter_by(category='Promotion-Pitch').all()
    
    return render_template('promo_pitch.html', promotion_pitches=promotion_pitches)


@main.route('/interviews')
def get_interviews():
    interview_pitches = Pitch.query.filter_by(category='Interview-Pitch').all()
    
    return render_template('interview_pitch.html', interview_pitches=interview_pitches)

@main.route('/products')
def get_products():
    product_pitches = Pitch.query.filter_by(category='Product-Pitch').all()
    
    return render_template('product_pitch.html', product_pitches=product_pitches)

    
    
    

app/templates/addcomments.html
{%extends 'base.html'%}
{%import 'bootstrap/wtf.html' as wtf%}


{%block content%}
{{super()}}
        <h1>Add comment for {{pitch_comment.category}}</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <!--Flash message -->
      {% for message in get_flashed_messages() %}
      <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message }}
      </div>
    {% endfor %}
                {{wtf.quick_form(comment_form)}}
            </div>
        </div>
    <div class="col-md-2"></div>
    </div>

   

{%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PitchSocial</title>
    {%block styles%}

    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {%endblock%}
</head>
<body>
    {%block content%}
        {%include "navbar.html" %}



        
    {%endblock%}


    
    {%block footer%}
    {%include "footer.html"%}
    {%endblock%}
    
</body>
</html>

app/templates/footer.html
<!-- <div class="footer-dark">
  <footer>
      <div class="container">
          <div class="row">
              <div class="col-md-8">
            <p class="copyright">Samuel Aronda © 2020</p>
        </div>
              
              
          </divc>
         
      </div>
  </footer> 
  </div> -->

app/templates/home.html
{%extends 'base.html'%}

{%block content%}
    {{super()}}

        <div class="container">
        <div class="jumbotron">
        <h1 align="center">WELCOME TO PITCH SOCIAL</h1>

          <h4 align="center">Write a pitch of your liking and get instant feedback from fellow pitchers</h4>
          <div class="center">
            <a class="btn btn-primary mx-auto" href="{{url_for('main.add_pitch')}}">
                CREATE PITCH HERE
            </a>
        </div>
        </div>
        <div class="row">
        <div ></div>
        {%for pitch in pitches%}

                <div class="card text-white bg-info m-3" style="width: 20rem;">
                    <div class="card-body">
                      <h5 class="card-title">{{pitch.category}}</h5>
                      
                      <p class="card-text">{{pitch.mintute_pitch}}</p>
                      <strong><p class="card-text">Posted by:{{pitch.user.username}}</p></strong>
                      <a style="color: white;" href="/addcomment/{{pitch.id}}" class="card-link">Add Comment</a>
                      <a style="color: white;" href="/viewcomments/{{pitch.id}}" class="card-link">View Comments</a>
                    </div>
                  </div>
        {%endfor%}
                  
    </div>
  </div>
{%endblock%}



{%block footer%}
    {{super()}}
    
{%endblock%}


    

app/templates/interview_pitch.html
{%extends 'base.html'%}
{%block content%}
{{super()}}
<div class="product">
  <h1 style="color:#0a369d;" align="center">Interview Pitches</h1>
{%if interview_pitches %}
<div class="row">
{%for interview in interview_pitches%}

  
      <div  class="card text-white bg-primary m-3" style="width: 20rem;">
          <div class="card-body">
            <h5 class="card-title">{{interview.category}}</h5>
            
            <p class="card-text">{{interview.mintute_pitch}}</p>
            <a style="color: white;" href="/addcomment/{{interview.id}}" class="card-link">Add Comment</a>
            <a style="color: white;" href="/viewcomments/{{interview.id}}" class="card-link">View Comments</a>
          </div>
        </div>
  
  
  

{%endfor%}
</div>
{%else%}
  <h3>No Interview Pitches found</h3>
{%endif%}
</div>

{%endblock%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand" style="color: white;" href="#">PitchSocial</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link"style="color: white;" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"style="color: white;" href="{{url_for('main.get_interviews')}}">Interview</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"style="color: white;" href="{{url_for('main.get_promotions')}}">Promotion</a>
        </li>
        <li class="nav-item">
            <a class="nav-link"style="color: white;" href="{{url_for('main.get_products')}}">Product</a>
          </li>
      </ul>
    </div>
   
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li style="color:white;padding:15px;">Welcome {{current_user.username}}</li>
      <li style="color:white;padding:15px;"> <a href="{{url_for('main.user_profile',id=current_user.id)}}">Profile</a></li>
      <li style="color:white;padding:15px;"><a type="btn btn-success" href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}
      <li style="color:white;padding:15px;"><a type="btn" href="{{url_for('auth.login')}}">Sign in</a></li>
      {%endif%}
    </ul>
  
  </nav>

app/templates/pitch.html
{%extends 'base.html'%}
{%import 'bootstrap/wtf.html' as wtf%}


{%block content%}
{{super()}}
        <h1>ADD PITCH</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {{wtf.quick_form(pitch_form)}}
            </div>
        </div>
    <div class="col-md-2"></div>
    </div>
{%endblock%}

app/templates/product_pitch.html
{%extends 'base.html'%}
{%block content%}
{{super()}}
<div class="product">
    <h1 style="color:#0a369d;" align="center">Product Pitches</h1>
{%if product_pitches %}
<div class="row">
{%for product in product_pitches%}

    
        <div  class="card text-white bg-primary m-3" style="width: 20rem;">
            <div class="card-body">
              <h5 class="card-title">{{product.category}}</h5>
              
              <p class="card-text">{{product.mintute_pitch}}</p>
              <a style="color: white;" href="/addcomment/{{product.id}}" class="card-link">Add Comment</a>
              <a style="color: white;" href="/viewcomments/{{product.id}}" class="card-link">View Comments</a>
            </div>
          </div>
    
    
    

{%endfor%}
</div>
{%else%}
    <h3>No Product Pitches found</h3>
{%endif%}
</div>

{%endblock%}

app/templates/prof/profile.html
{%extends 'base.html'%}

{%block content%}
{{super()}}
<div class="container">
    
    <h1 align="center">{{user.username}} <br> 
        <hr>
        Pitches</h1> 
    {%for pitch in pitches%}
    <div class="row">
        <div class="col-md-8">

            
            <div class="card text-white bg-success mb-3" style="width: 50rem;">
                <div class="card-body">
                  <h5 class="card-title">{{pitch.category}}</h5>
                  
                  <p class="card-text">{{pitch.mintute_pitch}}</p>
                  
                </div>
              </div>

        </div>
    </div>
    {%endfor%}


    <section>
        <div class="row">
            <div class="col-md-6">
                {% if user.profile_image %}

    <img src="{{url_for('static',filename=user.profile_image)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

                {% if user == current_user %}     
    <form  action="/updatepic/{{user.id}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input class="btn btn-primary" placeholder="Submit photo" type="submit">
    </form>
    {% endif %}
            </div>
        </div>

    </section>

</div>

{%endblock%}

app/templates/promo_pitch.html
{%extends 'base.html'%}
{%block content%}
{{super()}}
    <div>
    <div class="promo">
    <h1 style="color: #0a369d;" align="center">Promotion Pitches</h1>
    <div class="row">
{%for promo in promotion_pitches%}

        <div class="card text-white bg-primary m-3" style="width: 20rem;">
            <div class="card-body">
              <h5 class="card-title">{{promo.category}}</h5>
              
              <p class="card-text">{{promo.mintute_pitch}}</p>
              <strong><p class="card-text">Posted: {{promo.user.username}}</p></strong>
              <a style="color: white;" href="/addcomment/{{promo.id}}" class="card-link">Add Comment</a>
              <a style="color: white;" href="/viewcomments/{{promo.id}}" class="card-link">View Comments</a>
            </div>
          </div>
    
    
    

{%endfor%}
</div>
</div>

{%endblock%}

app/templates/viewcomments.html
{%extends 'base.html'%}

{%block content%}
    {{super()}}
<div class="container">
    <h1 align="center">Comments</h1 a>
{%if fetch_comments%}
{%for comm in fetch_comments%}

        <div class="row">
            <div class="col-md-2"></div>
            
            <div class= "col-md-8">
                <div class="card text-white bg-primary mb-3" style="width: 50rem;">
                    <div class="card-body">
                      <h5 class="card-title">{{comm.pitch.category}}</h5>
                      
                      <p class="card-text">{{comm.comment}}</p>
                      <p class="card-text">Posted by:{{comm.user.username}}</p>
                      
                    </div>
                  </div>
            
            </div>
            
        </div>
        {%endfor%}
    {%else%}
        <h3>No comments made </h3>
    {%endif%}
    </div>
    {%endblock%}